"""orcamento: adicionar conta \xc3\xa0 chave unica do RREO

Revision ID: 229408583727
Revises: b46441a737ca
Create Date: 2026-04-16 22:32:03.874028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229408583727'
down_revision: Union[str, None] = 'b46441a737ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execucao_orcamentaria', 'conta',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_exec_orc_unique'), table_name='execucao_orcamentaria')
    op.create_index('ix_exec_orc_unique', 'execucao_orcamentaria', ['orgao_id', 'exercicio', 'periodo', 'tipo_relatorio', 'anexo', 'cod_conta', 'coluna', 'conta'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exec_orc_unique', table_name='execucao_orcamentaria')
    op.create_index(op.f('ix_exec_orc_unique'), 'execucao_orcamentaria', ['orgao_id', 'exercicio', 'periodo', 'tipo_relatorio', 'anexo', 'cod_conta', 'coluna'], unique=True)
    op.alter_column('execucao_orcamentaria', 'conta',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
