"""rgf: indicadores_fiscais

Revision ID: 3710dc007ebc
Revises: fc820302f32a
Create Date: 2026-04-16 22:56:52.360434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3710dc007ebc'
down_revision: Union[str, None] = 'fc820302f32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores_fiscais',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('limite_legal', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('situacao', sa.String(length=30), nullable=False),
    sa.Column('fonte_relatorio', sa.String(length=10), nullable=False),
    sa.Column('fonte_exercicio', sa.Integer(), nullable=True),
    sa.Column('fonte_periodo', sa.Integer(), nullable=True),
    sa.Column('orgao_id', sa.UUID(), nullable=False),
    sa.Column('calculado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indic_fisc_unique', 'indicadores_fiscais', ['orgao_id', 'exercicio', 'periodo', 'codigo'], unique=True)
    op.create_index(op.f('ix_indicadores_fiscais_codigo'), 'indicadores_fiscais', ['codigo'], unique=False)
    op.create_index(op.f('ix_indicadores_fiscais_exercicio'), 'indicadores_fiscais', ['exercicio'], unique=False)
    op.create_index(op.f('ix_indicadores_fiscais_orgao_id'), 'indicadores_fiscais', ['orgao_id'], unique=False)
    op.create_index(op.f('ix_indicadores_fiscais_periodo'), 'indicadores_fiscais', ['periodo'], unique=False)
    op.create_index(op.f('ix_indicadores_fiscais_situacao'), 'indicadores_fiscais', ['situacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indicadores_fiscais_situacao'), table_name='indicadores_fiscais')
    op.drop_index(op.f('ix_indicadores_fiscais_periodo'), table_name='indicadores_fiscais')
    op.drop_index(op.f('ix_indicadores_fiscais_orgao_id'), table_name='indicadores_fiscais')
    op.drop_index(op.f('ix_indicadores_fiscais_exercicio'), table_name='indicadores_fiscais')
    op.drop_index(op.f('ix_indicadores_fiscais_codigo'), table_name='indicadores_fiscais')
    op.drop_index('ix_indic_fisc_unique', table_name='indicadores_fiscais')
    op.drop_table('indicadores_fiscais')
    # ### end Alembic commands ###
