"""initial schema: orgaos, fornecedores, contratacoes, contratos, itens_pca

Revision ID: 8e5653918a55
Revises: 
Create Date: 2026-04-12 18:59:17.973313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5653918a55'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Extensões necessárias em ambientes limpos (ex: Cloud SQL).
    # No dev local já são criadas pelo `scripts/init-db.sql` via docker-compose;
    # IF NOT EXISTS mantém o op idempotente.
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute("CREATE EXTENSION IF NOT EXISTS unaccent")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cpf_cnpj'), 'fornecedores', ['cpf_cnpj'], unique=True)
    op.create_table('itens_pca',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pncp_id', sa.String(length=100), nullable=True),
    sa.Column('ano_exercicio', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_executado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('unidade_requisitante', sa.String(length=255), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itens_pca_ano_exercicio'), 'itens_pca', ['ano_exercicio'], unique=False)
    op.create_index(op.f('ix_itens_pca_pncp_id'), 'itens_pca', ['pncp_id'], unique=True)
    op.create_table('orgaos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('esfera', sa.String(length=50), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('municipio', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_cnpj'), 'orgaos', ['cnpj'], unique=True)
    op.create_table('contratacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pncp_id', sa.String(length=100), nullable=True),
    sa.Column('numero_sequencial', sa.Integer(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('numero_processo', sa.String(length=100), nullable=True),
    sa.Column('orgao_id', sa.UUID(), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor_estimado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_homologado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('data_publicacao', sa.Date(), nullable=True),
    sa.Column('data_abertura', sa.Date(), nullable=True),
    sa.Column('data_homologacao', sa.Date(), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contratacoes_modalidade', 'contratacoes', ['modalidade'], unique=False)
    op.create_index('ix_contratacoes_orgao_ano', 'contratacoes', ['orgao_id', 'ano'], unique=False)
    op.create_index(op.f('ix_contratacoes_pncp_id'), 'contratacoes', ['pncp_id'], unique=True)
    op.create_table('contratos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pncp_id', sa.String(length=100), nullable=True),
    sa.Column('numero_contrato', sa.String(length=100), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('contratacao_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('valor_inicial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_atual', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_aditivos', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_assinatura', sa.Date(), nullable=True),
    sa.Column('data_inicio_vigencia', sa.Date(), nullable=True),
    sa.Column('data_fim_vigencia', sa.Date(), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('subcategoria', sa.String(length=100), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contratacao_id'], ['contratacoes.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_data_fim_vigencia'), 'contratos', ['data_fim_vigencia'], unique=False)
    op.create_index('ix_contratos_fornecedor', 'contratos', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_contratos_pncp_id'), 'contratos', ['pncp_id'], unique=True)
    op.create_index('ix_contratos_vigencia', 'contratos', ['data_fim_vigencia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contratos_vigencia', table_name='contratos')
    op.drop_index(op.f('ix_contratos_pncp_id'), table_name='contratos')
    op.drop_index('ix_contratos_fornecedor', table_name='contratos')
    op.drop_index(op.f('ix_contratos_data_fim_vigencia'), table_name='contratos')
    op.drop_table('contratos')
    op.drop_index(op.f('ix_contratacoes_pncp_id'), table_name='contratacoes')
    op.drop_index('ix_contratacoes_orgao_ano', table_name='contratacoes')
    op.drop_index('ix_contratacoes_modalidade', table_name='contratacoes')
    op.drop_table('contratacoes')
    op.drop_index(op.f('ix_orgaos_cnpj'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_itens_pca_pncp_id'), table_name='itens_pca')
    op.drop_index(op.f('ix_itens_pca_ano_exercicio'), table_name='itens_pca')
    op.drop_table('itens_pca')
    op.drop_index(op.f('ix_fornecedores_cpf_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
