"""extensao orcamento: execucao_orcamentaria (RREO)

Revision ID: b46441a737ca
Revises: 8e5653918a55
Create Date: 2026-04-16 22:22:17.700220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46441a737ca'
down_revision: Union[str, None] = '8e5653918a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execucao_orcamentaria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.Column('periodicidade', sa.String(length=5), nullable=True),
    sa.Column('tipo_relatorio', sa.String(length=10), nullable=False),
    sa.Column('anexo', sa.String(length=100), nullable=False),
    sa.Column('rotulo', sa.String(length=255), nullable=True),
    sa.Column('coluna', sa.String(length=255), nullable=False),
    sa.Column('cod_conta', sa.String(length=255), nullable=False),
    sa.Column('conta', sa.Text(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('orgao_id', sa.UUID(), nullable=False),
    sa.Column('cod_ibge', sa.String(length=7), nullable=False),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exec_orc_exerc_anexo', 'execucao_orcamentaria', ['exercicio', 'anexo'], unique=False)
    op.create_index('ix_exec_orc_unique', 'execucao_orcamentaria', ['orgao_id', 'exercicio', 'periodo', 'tipo_relatorio', 'anexo', 'cod_conta', 'coluna'], unique=True)
    op.create_index(op.f('ix_execucao_orcamentaria_anexo'), 'execucao_orcamentaria', ['anexo'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_cod_conta'), 'execucao_orcamentaria', ['cod_conta'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_cod_ibge'), 'execucao_orcamentaria', ['cod_ibge'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_coluna'), 'execucao_orcamentaria', ['coluna'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_exercicio'), 'execucao_orcamentaria', ['exercicio'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_orgao_id'), 'execucao_orcamentaria', ['orgao_id'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_periodo'), 'execucao_orcamentaria', ['periodo'], unique=False)
    op.create_index(op.f('ix_execucao_orcamentaria_tipo_relatorio'), 'execucao_orcamentaria', ['tipo_relatorio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execucao_orcamentaria_tipo_relatorio'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_periodo'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_orgao_id'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_exercicio'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_coluna'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_cod_ibge'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_cod_conta'), table_name='execucao_orcamentaria')
    op.drop_index(op.f('ix_execucao_orcamentaria_anexo'), table_name='execucao_orcamentaria')
    op.drop_index('ix_exec_orc_unique', table_name='execucao_orcamentaria')
    op.drop_index('ix_exec_orc_exerc_anexo', table_name='execucao_orcamentaria')
    op.drop_table('execucao_orcamentaria')
    # ### end Alembic commands ###
