"""ibge: dados_municipio

Revision ID: fc820302f32a
Revises: 229408583727
Create Date: 2026-04-16 22:41:46.948115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc820302f32a'
down_revision: Union[str, None] = '229408583727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dados_municipio',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orgao_id', sa.UUID(), nullable=False),
    sa.Column('codigo_ibge', sa.String(length=7), nullable=False),
    sa.Column('exercicio', sa.Integer(), nullable=False),
    sa.Column('nome_municipio', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('populacao', sa.Integer(), nullable=True),
    sa.Column('pib_corrente', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pib_per_capita', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('fonte', sa.String(length=20), nullable=False),
    sa.Column('dados_brutos', sa.Text(), nullable=True),
    sa.Column('ingerido_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orgao_id'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dados_mun_unique', 'dados_municipio', ['orgao_id', 'exercicio'], unique=True)
    op.create_index(op.f('ix_dados_municipio_codigo_ibge'), 'dados_municipio', ['codigo_ibge'], unique=False)
    op.create_index(op.f('ix_dados_municipio_exercicio'), 'dados_municipio', ['exercicio'], unique=False)
    op.create_index(op.f('ix_dados_municipio_orgao_id'), 'dados_municipio', ['orgao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dados_municipio_orgao_id'), table_name='dados_municipio')
    op.drop_index(op.f('ix_dados_municipio_exercicio'), table_name='dados_municipio')
    op.drop_index(op.f('ix_dados_municipio_codigo_ibge'), table_name='dados_municipio')
    op.drop_index('ix_dados_mun_unique', table_name='dados_municipio')
    op.drop_table('dados_municipio')
    # ### end Alembic commands ###
